import { generatePricebook } from './research.js';
import { generateFakeIdentity } from './mergeDemo.js';
import { serializeOrganization } from './serialize.js';
import { saveOrg } from '../orgStorageService.js';
import logger from '../../utils/logger.js';

// A synthetic multi-industry demo org: one WORK AREA per industry, each with its
// own categories + items generated by a dedicated per-industry pricebook call,
// then merged into a single org with a random fake identity. Reuses the exact
// same building blocks as the normal generate flow (generatePricebook +
// generateFakeIdentity + serializeOrganization), so the resulting org deploys
// identically. Images are generated later via the existing bulk-image flow.

// Pool of common home-services trades to draw industries from.
const INDUSTRY_POOL = [
  'HVAC', 'Roofing', 'Plumbing', 'Electrical', 'Solar', 'Insulation',
  'Landscaping', 'Painting', 'Flooring', 'Garage Doors', 'Windows & Doors',
  'Pest Control', 'Concrete & Masonry', 'Fencing', 'Gutters', 'Drywall',
  'Tree Service', 'Pool Service', 'Siding', 'Water Damage Restoration',
];

// Regions used for the fake identity + pricing context (US markets).
const REGION_POOL = [
  'Austin, TX', 'Denver, CO', 'Phoenix, AZ', 'Charlotte, NC', 'Tampa, FL',
  'Nashville, TN', 'Sacramento, CA', 'Columbus, OH', 'Salt Lake City, UT',
];

// Same default staffing the OrgGenerator UI uses.
const DEFAULT_ROLE_DISTRIBUTION = [
  { role: 'Admin', count: 2 },
  { role: 'Ops Manager', count: 2 },
  { role: 'Sales Admin', count: 1 },
  { role: 'Sales Member', count: 3 },
  { role: 'Client Coordinator', count: 1 },
  { role: 'Crew Leader', count: 4 },
  { role: 'Crew Member', count: 8 },
];

const DEFAULT_TIMEZONE = 'America/Los_Angeles';

function slugify(name) {
  return String(name || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

// Fisher-Yates on a copy, then take the first n.
function pickRandom(arr, n) {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.min(n, copy.length));
}

const lower = (s) => String(s || '').trim().toLowerCase();

// Normalize an industry list: trim, drop empties, dedupe (case-insensitive), cap.
function normalizeIndustries(list) {
  if (!Array.isArray(list)) return [];
  return [...new Map(
    list.map((s) => String(s || '').trim()).filter(Boolean).map((s) => [s.toLowerCase(), s]),
  ).values()].slice(0, 12);
}

/**
 * Create a multi-industry org SHELL — identity (name, logo-less), one branch,
 * default branch config + proposal content, default users, and ONE EMPTY WORK
 * AREA per industry. No pricebook o3 calls here (just the fast fake-identity
 * call), so it returns in seconds. Each work area's catalog is generated later,
 * per industry, from the org detail page. Returns the saved org.
 */
export async function createMultiIndustryShell(params, openai) {
  const industries = normalizeIndustries(params.industries);
  if (industries.length === 0) throw new Error('Provide at least one industry');
  const region = (params.region || '').trim() || pickRandom(REGION_POOL, 1)[0];

  const identity = await generateFakeIdentity(
    { industry: 'multi-trade home services', region, services: industries, branchCount: 1 },
    openai,
  );
  const companyName = (params.companyName || '').trim() || identity.companyName;

  // Minimal pricebook: empty work areas (one per industry) + null config so
  // serializeOrganization fills BRANCH_CONFIG_DEFAULTS / PROPOSAL_CONTENT_DEFAULTS.
  const pricebook = {
    workAreas: industries.map((name) => ({ name, categories: [] })),
    categories: [],
    factors: [{ name: 'Standard', factor: 1.0, appliesTo: 'labor', alwaysEnabled: true }],
    additionalCosts: [],
    branchConfig: null,
    proposalContent: null,
    vehicleTemplates: [],
    equipmentTypes: [],
    subcontractedItems: [],
  };
  const input = {
    slug: slugify(companyName),
    companyName,
    domain: identity.domain || slugify(companyName),
    timezone: DEFAULT_TIMEZONE,
    branches: identity.branches?.length ? identity.branches : [{ name: 'Main Office', address: `100 Demo St, ${region}` }],
    roleDistribution: DEFAULT_ROLE_DISTRIBUTION,
    companyWebsite: '',
    industryContext: '',
  };
  const extracted = {
    industry: 'Multi-Industry Home Services',
    region,
    about: identity.about || '',
    phone: identity.phone || '',
    contractorLicense: identity.contractorLicense || '',
    financingTerms: [],
  };

  const org = serializeOrganization(input, extracted, pricebook);
  org.isDemo = true;
  org.multiIndustry = { industries, region };
  saveOrg(org);
  logger.info(`[multi-industry] shell created: ${org.slug} — ${industries.length} work areas`);
  return org;
}

// ── Incremental work-area management (add industry + fill its catalog) ────────

// Add an empty work area (industry) to an existing org. Pure — no AI.
export function addWorkAreaToOrg(org, name) {
  const clean = String(name || '').trim();
  if (!clean) throw new Error('Industry / work area name is required');
  const res = org.resources;
  if (res.workAreas.some((w) => lower(w.name) === lower(clean))) {
    throw new Error(`Work area "${clean}" already exists`);
  }
  res.workAreas.push({ name: clean, categories: [], factorNames: [] });
  org.stats = { ...(org.stats || {}), workAreas: res.workAreas.length };
  return org;
}

// Append one industry's generated pricebook into an existing org, attaching its
// categories to `workAreaName` (created if missing). Names are made unique vs
// the WHOLE org (append " (Industry)" on collision); new factors/additional
// costs are deduped in. Mutates + returns counts. Mirrors serialize's shapes.
function appendCatalogToOrg(org, workAreaName, industry, pricebook) {
  const res = org.resources;
  res.additionalCosts = res.additionalCosts || [];
  const usedCat = new Set(res.categories.map((c) => lower(c.name)));
  const usedItem = new Set(res.categories.flatMap((c) => (c.items || []).map((i) => lower(i.name))));
  const factorNames = new Set(res.factors.map((f) => lower(f.name)));
  const costNames = new Set(res.additionalCosts.map((c) => lower(c.name)));

  for (const f of pricebook.factors || []) {
    if (factorNames.has(lower(f.name))) continue;
    factorNames.add(lower(f.name));
    res.factors.push({ name: f.name, factor: f.factor, appliesTo: f.appliesTo, alwaysEnabled: f.alwaysEnabled || false });
  }
  for (const c of pricebook.additionalCosts || []) {
    if (costNames.has(lower(c.name))) continue;
    costNames.add(lower(c.name));
    res.additionalCosts.push({ name: c.name, cost: c.cost, appliesTo: c.appliesTo });
  }
  const validFactor = (n) => factorNames.has(lower(n));
  const validCost = (n) => costNames.has(lower(n));

  let wa = res.workAreas.find((w) => lower(w.name) === lower(workAreaName));
  if (!wa) { wa = { name: workAreaName, categories: [], factorNames: [] }; res.workAreas.push(wa); }

  let addedCats = 0;
  let addedItems = 0;
  for (const cat of pricebook.categories || []) {
    let catName = cat.name;
    if (usedCat.has(lower(catName))) catName = `${cat.name} (${industry})`;
    usedCat.add(lower(catName));
    const items = (cat.items || []).map((item) => {
      let name = item.name;
      if (usedItem.has(lower(name))) name = `${item.name} (${industry})`;
      usedItem.add(lower(name));
      addedItems += 1;
      return {
        name,
        itemInfo: item.itemInfo || item.notes || '',
        unit: item.unit,
        materialCost: item.materialCost,
        laborHours: item.laborHours,
        multiplierOverride: item.multiplierOverride ?? null,
        subItem: false,
        requiresInfo: item.requiresInfo ?? false,
        factorNames: (item.factorNames || []).filter(validFactor),
        additionalCostNames: (item.additionalCostNames || []).filter(validCost),
        imageUrl: item.imageUrl || null,
        imageSource: item.imageSource || null,
      };
    });
    res.categories.push({ name: catName, title: cat.title || catName, factorNames: (cat.factorNames || []).filter(validFactor), items });
    if (!wa.categories.includes(catName)) wa.categories.push(catName);
    addedCats += 1;
  }

  org.stats = {
    ...(org.stats || {}),
    categories: res.categories.length,
    items: res.categories.reduce((s, c) => s + (c.items?.length || 0), 0),
    workAreas: res.workAreas.length,
    factors: res.factors.length,
  };
  return { addedCats, addedItems };
}

/**
 * Generate one industry's catalog (categories + items) and append it to a work
 * area of an existing org. `params.industry` defaults to the work area name but
 * can be overridden (so a work area can represent a custom industry). Streams
 * progress; saves the org. Returns `{ success, addedCats, addedItems }`.
 */
export async function generateWorkAreaCatalog(org, params, openai, onStep) {
  const log = [];
  const step = (name, status, detail = '') => {
    const entry = { name, status, detail, ts: new Date().toISOString() };
    log.push(entry);
    onStep?.(entry);
    logger.info(`[work-area-catalog] ${name}: ${status} ${detail}`);
  };

  const workArea = String(params.workArea || '').trim();
  if (!workArea) throw new Error('workArea is required');
  const industry = String(params.industry || workArea).trim();
  const categoryCount = Math.max(3, Math.min(12, Number(params.categoriesPerIndustry) || 7));
  const itemsPerCategory = Math.max(3, Math.min(12, Number(params.itemsPerCategory) || 6));
  const region = org.region || org.multiIndustry?.region || 'United States';

  try {
    step('pricebook', 'running', `${industry} → "${workArea}"`);
    const pricebook = await generatePricebook(
      { industry, region, companyName: org.name, workAreaCount: 1, categoryCount, itemsPerCategory, synthesized: true, services: [industry], catalogOnly: true },
      openai,
    );
    step('pricebook', 'done', `${pricebook.categories?.length || 0} categories generated`);

    step('append', 'running');
    const { addedCats, addedItems } = appendCatalogToOrg(org, workArea, industry, pricebook);
    saveOrg(org);
    step('complete', 'done', `+${addedCats} categories, +${addedItems} items in "${workArea}"`);
    return { success: true, org, addedCats, addedItems, log };
  } catch (err) {
    step('error', 'failed', err.message);
    return { success: false, error: err.message, log };
  }
}

/**
 * Merge N per-industry pricebooks into one. Each industry becomes exactly one
 * work area (named after the industry) holding that industry's categories.
 * Category + item names are made globally unique (append " (Industry)" on a
 * cross-industry collision) so validateOrgForDeployment passes. Factors and
 * additional costs are deduped by name (first wins); branch config + proposal
 * content are taken from the first industry (a diversified company needs one).
 */
export function mergePricebooks(entries) {
  const usedCat = new Set();
  const usedItem = new Set();
  const categories = [];
  const workAreas = [];
  const factors = [];
  const additionalCosts = [];
  const factorNames = new Set();
  const costNames = new Set();
  const vehicleTemplates = [];
  const seenVehicles = new Set();
  const equipmentTypes = new Set();
  let branchConfig = null;
  let proposalContent = null;

  for (const { industry, pricebook } of entries) {
    if (!branchConfig && pricebook.branchConfig) branchConfig = pricebook.branchConfig;
    if (!proposalContent && pricebook.proposalContent) proposalContent = pricebook.proposalContent;

    const areaCategories = [];
    for (const cat of pricebook.categories || []) {
      let catName = cat.name;
      if (usedCat.has(lower(catName))) catName = `${cat.name} (${industry})`;
      usedCat.add(lower(catName));

      const items = (cat.items || []).map((item) => {
        let name = item.name;
        if (usedItem.has(lower(name))) name = `${item.name} (${industry})`;
        usedItem.add(lower(name));
        return { ...item, name };
      });

      categories.push({ ...cat, name: catName, items });
      areaCategories.push(catName);
    }
    // One work area per industry — deterministic, regardless of how the model
    // named its own work areas.
    workAreas.push({ name: industry, categories: areaCategories });

    for (const f of pricebook.factors || []) {
      if (factorNames.has(lower(f.name))) continue;
      factorNames.add(lower(f.name));
      factors.push(f);
    }
    for (const c of pricebook.additionalCosts || []) {
      if (costNames.has(lower(c.name))) continue;
      costNames.add(lower(c.name));
      additionalCosts.push(c);
    }
    for (const v of pricebook.vehicleTemplates || []) {
      const key = `${lower(v.make)}|${lower(v.model)}|${v.year}`;
      if (seenVehicles.has(key)) continue;
      seenVehicles.add(key);
      vehicleTemplates.push(v);
    }
    for (const e of pricebook.equipmentTypes || []) equipmentTypes.add(e);
  }

  return {
    workAreas,
    categories,
    factors,
    additionalCosts,
    branchConfig,
    proposalContent,
    vehicleTemplates,
    equipmentTypes: [...equipmentTypes],
    // Subcontracted items are skipped for the multi-industry demo to keep the
    // merge simple (they're optional and would need their own dedup pass).
    subcontractedItems: [],
  };
}

/**
 * Build a synthetic multi-industry demo org end to end. Streams progress via
 * `onStep({ name, status, detail })` (same shape as deployOrg). Returns
 * `{ success, org, slug, industries, region, log }`.
 */
export async function generateMultiIndustryDemo(params, openai, onStep) {
  const log = [];
  const step = (name, status, detail = '') => {
    const entry = { name, status, detail, ts: new Date().toISOString() };
    log.push(entry);
    onStep?.(entry);
    logger.info(`[multi-industry] ${name}: ${status} ${detail}`);
  };

  const industryCount = Math.max(2, Math.min(12, Number(params.industryCount) || 8));
  const categoriesPerIndustry = Math.max(3, Math.min(12, Number(params.categoriesPerIndustry) || 7));
  const itemsPerCategory = Math.max(3, Math.min(12, Number(params.itemsPerCategory) || 6));

  // Custom industries win when provided; otherwise pick at random from the pool.
  const customIndustries = normalizeIndustries(params.industries);

  try {
    const industries = customIndustries.length > 0
      ? customIndustries
      : pickRandom(INDUSTRY_POOL, industryCount);
    const region = params.region || pickRandom(REGION_POOL, 1)[0];
    step('plan', 'done', `${industries.length} industries (${customIndustries.length ? 'custom' : 'random'}) in ${region}: ${industries.join(', ')}`);

    // 1. Fake identity for a diversified home-services company.
    step('identity', 'running');
    const identity = await generateFakeIdentity(
      { industry: 'multi-trade home services', region, services: industries, branchCount: 1 },
      openai,
    );
    step('identity', 'done', `${identity.companyName} (${identity.domain})`);

    // 2. One pricebook per industry (each = one work area). Resilient: a failed
    // industry is skipped, not fatal.
    const entries = [];
    for (let i = 0; i < industries.length; i++) {
      const industry = industries[i];
      step('pricebook', 'running', `${industry} (${i + 1}/${industries.length})`);
      try {
        const pricebook = await generatePricebook(
          {
            industry,
            region,
            companyName: identity.companyName,
            companyAbout: identity.about,
            workAreaCount: 1,
            categoryCount: categoriesPerIndustry,
            itemsPerCategory,
            synthesized: true,
            services: [industry],
          },
          openai,
        );
        entries.push({ industry, pricebook });
        const items = (pricebook.categories || []).reduce((s, c) => s + (c.items?.length || 0), 0);
        step('pricebook', 'done', `${industry}: ${pricebook.categories?.length || 0} categories, ${items} items`);
      } catch (err) {
        step('pricebook', 'failed', `${industry}: ${err.message}`);
      }
    }
    if (entries.length === 0) throw new Error('No industries were generated successfully');

    // 3. Merge into a single pricebook (one work area per industry).
    step('merge', 'running');
    const merged = mergePricebooks(entries);
    const totalItems = merged.categories.reduce((s, c) => s + (c.items?.length || 0), 0);
    step('merge', 'done', `${merged.workAreas.length} work areas, ${merged.categories.length} categories, ${totalItems} items`);

    // 4. Assemble input + extracted for serializeOrganization (reused verbatim).
    const input = {
      slug: slugify(identity.companyName),
      companyName: identity.companyName,
      domain: identity.domain || slugify(identity.companyName),
      timezone: DEFAULT_TIMEZONE,
      branches: identity.branches?.length ? identity.branches : [{ name: 'Main Office', address: `100 Demo St, ${region}` }],
      roleDistribution: DEFAULT_ROLE_DISTRIBUTION,
      companyWebsite: '',
      industryContext: '',
    };
    const extracted = {
      industry: 'Multi-Industry Home Services',
      region,
      about: identity.about || '',
      phone: identity.phone || '',
      contractorLicense: identity.contractorLicense || '',
      financingTerms: [],
    };

    step('assemble', 'running');
    const org = serializeOrganization(input, extracted, merged);
    org.isDemo = true;
    org.multiIndustry = { industries: entries.map((e) => e.industry), region };
    saveOrg(org);
    step('assemble', 'done', `Saved org ${org.slug}`);

    step('complete', 'done', `${org.name} — ${merged.workAreas.length} industries, ${totalItems} items`);
    return { success: true, org, slug: org.slug, industries: entries.map((e) => e.industry), region, log };
  } catch (err) {
    step('error', 'failed', err.message);
    return { success: false, error: err.message, log };
  }
}
